/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FounderIndexRouteImport } from './routes/founder.index'
import { Route as TeamWorkloadRouteImport } from './routes/team.workload'
import { Route as TeamHiringRouteImport } from './routes/team.hiring'
import { Route as TeamCheckinsRouteImport } from './routes/team.checkins'
import { Route as SpaceSpaceIdRouteImport } from './routes/space.$spaceId'
import { Route as PillarPillarIdRouteImport } from './routes/pillar.$pillarId'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as FounderVenturesRouteImport } from './routes/founder.ventures'
import { Route as FounderTeamRouteImport } from './routes/founder.team'
import { Route as FounderSettingsRouteImport } from './routes/founder.settings'
import { Route as FounderPipelineRouteImport } from './routes/founder.pipeline'
import { Route as FounderNetworkRouteImport } from './routes/founder.network'
import { Route as FounderMarketIntelRouteImport } from './routes/founder.market-intel'
import { Route as FounderInitiativesRouteImport } from './routes/founder.initiatives'
import { Route as FounderFinanceRouteImport } from './routes/founder.finance'
import { Route as FounderClientsRouteImport } from './routes/founder.clients'
import { Route as FounderAiAgentsRouteImport } from './routes/founder.ai-agents'
import { Route as SpaceSpaceIdListListIdRouteImport } from './routes/space.$spaceId.list.$listId'
import { Route as SpaceSpaceIdFolderFolderIdRouteImport } from './routes/space.$spaceId.folder.$folderId'
import { Route as FounderTeamJobsJobIdRouteImport } from './routes/founder.team.jobs.$jobId'
import { Route as FounderSettingsUsersIdRouteImport } from './routes/founder.settings.users.$id'
import { Route as SpaceSpaceIdListListIdTaskTaskIdRouteImport } from './routes/space.$spaceId.list.$listId.task.$taskId'
import { Route as SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRouteImport } from './routes/space.$spaceId.list.$listId.task.$taskId.subtask.$subtaskId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIndexRoute = FounderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FounderRoute,
} as any)
const TeamWorkloadRoute = TeamWorkloadRouteImport.update({
  id: '/team/workload',
  path: '/team/workload',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamHiringRoute = TeamHiringRouteImport.update({
  id: '/team/hiring',
  path: '/team/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCheckinsRoute = TeamCheckinsRouteImport.update({
  id: '/team/checkins',
  path: '/team/checkins',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpaceIdRoute = SpaceSpaceIdRouteImport.update({
  id: '/space/$spaceId',
  path: '/space/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarPillarIdRoute = PillarPillarIdRouteImport.update({
  id: '/pillar/$pillarId',
  path: '/pillar/$pillarId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderVenturesRoute = FounderVenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => FounderRoute,
} as any)
const FounderTeamRoute = FounderTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => FounderRoute,
} as any)
const FounderSettingsRoute = FounderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FounderRoute,
} as any)
const FounderPipelineRoute = FounderPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => FounderRoute,
} as any)
const FounderNetworkRoute = FounderNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => FounderRoute,
} as any)
const FounderMarketIntelRoute = FounderMarketIntelRouteImport.update({
  id: '/market-intel',
  path: '/market-intel',
  getParentRoute: () => FounderRoute,
} as any)
const FounderInitiativesRoute = FounderInitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => FounderRoute,
} as any)
const FounderFinanceRoute = FounderFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => FounderRoute,
} as any)
const FounderClientsRoute = FounderClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => FounderRoute,
} as any)
const FounderAiAgentsRoute = FounderAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => FounderRoute,
} as any)
const SpaceSpaceIdListListIdRoute = SpaceSpaceIdListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => SpaceSpaceIdRoute,
} as any)
const SpaceSpaceIdFolderFolderIdRoute =
  SpaceSpaceIdFolderFolderIdRouteImport.update({
    id: '/folder/$folderId',
    path: '/folder/$folderId',
    getParentRoute: () => SpaceSpaceIdRoute,
  } as any)
const FounderTeamJobsJobIdRoute = FounderTeamJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => FounderTeamRoute,
} as any)
const FounderSettingsUsersIdRoute = FounderSettingsUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => FounderSettingsRoute,
} as any)
const SpaceSpaceIdListListIdTaskTaskIdRoute =
  SpaceSpaceIdListListIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => SpaceSpaceIdListListIdRoute,
  } as any)
const SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute =
  SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRouteImport.update({
    id: '/subtask/$subtaskId',
    path: '/subtask/$subtaskId',
    getParentRoute: () => SpaceSpaceIdListListIdTaskTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/founder/ai-agents': typeof FounderAiAgentsRoute
  '/founder/clients': typeof FounderClientsRoute
  '/founder/finance': typeof FounderFinanceRoute
  '/founder/initiatives': typeof FounderInitiativesRoute
  '/founder/market-intel': typeof FounderMarketIntelRoute
  '/founder/network': typeof FounderNetworkRoute
  '/founder/pipeline': typeof FounderPipelineRoute
  '/founder/settings': typeof FounderSettingsRouteWithChildren
  '/founder/team': typeof FounderTeamRouteWithChildren
  '/founder/ventures': typeof FounderVenturesRoute
  '/people/$id': typeof PeopleIdRoute
  '/pillar/$pillarId': typeof PillarPillarIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/team/checkins': typeof TeamCheckinsRoute
  '/team/hiring': typeof TeamHiringRoute
  '/team/workload': typeof TeamWorkloadRoute
  '/founder/': typeof FounderIndexRoute
  '/founder/settings/users/$id': typeof FounderSettingsUsersIdRoute
  '/founder/team/jobs/$jobId': typeof FounderTeamJobsJobIdRoute
  '/space/$spaceId/folder/$folderId': typeof SpaceSpaceIdFolderFolderIdRoute
  '/space/$spaceId/list/$listId': typeof SpaceSpaceIdListListIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId': typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/files': typeof FilesRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/founder/ai-agents': typeof FounderAiAgentsRoute
  '/founder/clients': typeof FounderClientsRoute
  '/founder/finance': typeof FounderFinanceRoute
  '/founder/initiatives': typeof FounderInitiativesRoute
  '/founder/market-intel': typeof FounderMarketIntelRoute
  '/founder/network': typeof FounderNetworkRoute
  '/founder/pipeline': typeof FounderPipelineRoute
  '/founder/settings': typeof FounderSettingsRouteWithChildren
  '/founder/team': typeof FounderTeamRouteWithChildren
  '/founder/ventures': typeof FounderVenturesRoute
  '/people/$id': typeof PeopleIdRoute
  '/pillar/$pillarId': typeof PillarPillarIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/team/checkins': typeof TeamCheckinsRoute
  '/team/hiring': typeof TeamHiringRoute
  '/team/workload': typeof TeamWorkloadRoute
  '/founder': typeof FounderIndexRoute
  '/founder/settings/users/$id': typeof FounderSettingsUsersIdRoute
  '/founder/team/jobs/$jobId': typeof FounderTeamJobsJobIdRoute
  '/space/$spaceId/folder/$folderId': typeof SpaceSpaceIdFolderFolderIdRoute
  '/space/$spaceId/list/$listId': typeof SpaceSpaceIdListListIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId': typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRouteWithChildren
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/founder/ai-agents': typeof FounderAiAgentsRoute
  '/founder/clients': typeof FounderClientsRoute
  '/founder/finance': typeof FounderFinanceRoute
  '/founder/initiatives': typeof FounderInitiativesRoute
  '/founder/market-intel': typeof FounderMarketIntelRoute
  '/founder/network': typeof FounderNetworkRoute
  '/founder/pipeline': typeof FounderPipelineRoute
  '/founder/settings': typeof FounderSettingsRouteWithChildren
  '/founder/team': typeof FounderTeamRouteWithChildren
  '/founder/ventures': typeof FounderVenturesRoute
  '/people/$id': typeof PeopleIdRoute
  '/pillar/$pillarId': typeof PillarPillarIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/team/checkins': typeof TeamCheckinsRoute
  '/team/hiring': typeof TeamHiringRoute
  '/team/workload': typeof TeamWorkloadRoute
  '/founder/': typeof FounderIndexRoute
  '/founder/settings/users/$id': typeof FounderSettingsUsersIdRoute
  '/founder/team/jobs/$jobId': typeof FounderTeamJobsJobIdRoute
  '/space/$spaceId/folder/$folderId': typeof SpaceSpaceIdFolderFolderIdRoute
  '/space/$spaceId/list/$listId': typeof SpaceSpaceIdListListIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId': typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/clients'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/settings'
    | '/tasks'
    | '/founder/ai-agents'
    | '/founder/clients'
    | '/founder/finance'
    | '/founder/initiatives'
    | '/founder/market-intel'
    | '/founder/network'
    | '/founder/pipeline'
    | '/founder/settings'
    | '/founder/team'
    | '/founder/ventures'
    | '/people/$id'
    | '/pillar/$pillarId'
    | '/space/$spaceId'
    | '/team/checkins'
    | '/team/hiring'
    | '/team/workload'
    | '/founder/'
    | '/founder/settings/users/$id'
    | '/founder/team/jobs/$jobId'
    | '/space/$spaceId/folder/$folderId'
    | '/space/$spaceId/list/$listId'
    | '/space/$spaceId/list/$listId/task/$taskId'
    | '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/clients'
    | '/files'
    | '/inbox'
    | '/settings'
    | '/tasks'
    | '/founder/ai-agents'
    | '/founder/clients'
    | '/founder/finance'
    | '/founder/initiatives'
    | '/founder/market-intel'
    | '/founder/network'
    | '/founder/pipeline'
    | '/founder/settings'
    | '/founder/team'
    | '/founder/ventures'
    | '/people/$id'
    | '/pillar/$pillarId'
    | '/space/$spaceId'
    | '/team/checkins'
    | '/team/hiring'
    | '/team/workload'
    | '/founder'
    | '/founder/settings/users/$id'
    | '/founder/team/jobs/$jobId'
    | '/space/$spaceId/folder/$folderId'
    | '/space/$spaceId/list/$listId'
    | '/space/$spaceId/list/$listId/task/$taskId'
    | '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/clients'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/settings'
    | '/tasks'
    | '/founder/ai-agents'
    | '/founder/clients'
    | '/founder/finance'
    | '/founder/initiatives'
    | '/founder/market-intel'
    | '/founder/network'
    | '/founder/pipeline'
    | '/founder/settings'
    | '/founder/team'
    | '/founder/ventures'
    | '/people/$id'
    | '/pillar/$pillarId'
    | '/space/$spaceId'
    | '/team/checkins'
    | '/team/hiring'
    | '/team/workload'
    | '/founder/'
    | '/founder/settings/users/$id'
    | '/founder/team/jobs/$jobId'
    | '/space/$spaceId/folder/$folderId'
    | '/space/$spaceId/list/$listId'
    | '/space/$spaceId/list/$listId/task/$taskId'
    | '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRoute
  FilesRoute: typeof FilesRoute
  FounderRoute: typeof FounderRouteWithChildren
  InboxRoute: typeof InboxRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PillarPillarIdRoute: typeof PillarPillarIdRoute
  SpaceSpaceIdRoute: typeof SpaceSpaceIdRouteWithChildren
  TeamCheckinsRoute: typeof TeamCheckinsRoute
  TeamHiringRoute: typeof TeamHiringRoute
  TeamWorkloadRoute: typeof TeamWorkloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/': {
      id: '/founder/'
      path: '/'
      fullPath: '/founder/'
      preLoaderRoute: typeof FounderIndexRouteImport
      parentRoute: typeof FounderRoute
    }
    '/team/workload': {
      id: '/team/workload'
      path: '/team/workload'
      fullPath: '/team/workload'
      preLoaderRoute: typeof TeamWorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/hiring': {
      id: '/team/hiring'
      path: '/team/hiring'
      fullPath: '/team/hiring'
      preLoaderRoute: typeof TeamHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/checkins': {
      id: '/team/checkins'
      path: '/team/checkins'
      fullPath: '/team/checkins'
      preLoaderRoute: typeof TeamCheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space/$spaceId': {
      id: '/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/space/$spaceId'
      preLoaderRoute: typeof SpaceSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar/$pillarId': {
      id: '/pillar/$pillarId'
      path: '/pillar/$pillarId'
      fullPath: '/pillar/$pillarId'
      preLoaderRoute: typeof PillarPillarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/ventures': {
      id: '/founder/ventures'
      path: '/ventures'
      fullPath: '/founder/ventures'
      preLoaderRoute: typeof FounderVenturesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/team': {
      id: '/founder/team'
      path: '/team'
      fullPath: '/founder/team'
      preLoaderRoute: typeof FounderTeamRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/settings': {
      id: '/founder/settings'
      path: '/settings'
      fullPath: '/founder/settings'
      preLoaderRoute: typeof FounderSettingsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/pipeline': {
      id: '/founder/pipeline'
      path: '/pipeline'
      fullPath: '/founder/pipeline'
      preLoaderRoute: typeof FounderPipelineRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/network': {
      id: '/founder/network'
      path: '/network'
      fullPath: '/founder/network'
      preLoaderRoute: typeof FounderNetworkRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/market-intel': {
      id: '/founder/market-intel'
      path: '/market-intel'
      fullPath: '/founder/market-intel'
      preLoaderRoute: typeof FounderMarketIntelRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/initiatives': {
      id: '/founder/initiatives'
      path: '/initiatives'
      fullPath: '/founder/initiatives'
      preLoaderRoute: typeof FounderInitiativesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/finance': {
      id: '/founder/finance'
      path: '/finance'
      fullPath: '/founder/finance'
      preLoaderRoute: typeof FounderFinanceRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/clients': {
      id: '/founder/clients'
      path: '/clients'
      fullPath: '/founder/clients'
      preLoaderRoute: typeof FounderClientsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/ai-agents': {
      id: '/founder/ai-agents'
      path: '/ai-agents'
      fullPath: '/founder/ai-agents'
      preLoaderRoute: typeof FounderAiAgentsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/space/$spaceId/list/$listId': {
      id: '/space/$spaceId/list/$listId'
      path: '/list/$listId'
      fullPath: '/space/$spaceId/list/$listId'
      preLoaderRoute: typeof SpaceSpaceIdListListIdRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/space/$spaceId/folder/$folderId': {
      id: '/space/$spaceId/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/space/$spaceId/folder/$folderId'
      preLoaderRoute: typeof SpaceSpaceIdFolderFolderIdRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/founder/team/jobs/$jobId': {
      id: '/founder/team/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/founder/team/jobs/$jobId'
      preLoaderRoute: typeof FounderTeamJobsJobIdRouteImport
      parentRoute: typeof FounderTeamRoute
    }
    '/founder/settings/users/$id': {
      id: '/founder/settings/users/$id'
      path: '/users/$id'
      fullPath: '/founder/settings/users/$id'
      preLoaderRoute: typeof FounderSettingsUsersIdRouteImport
      parentRoute: typeof FounderSettingsRoute
    }
    '/space/$spaceId/list/$listId/task/$taskId': {
      id: '/space/$spaceId/list/$listId/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/space/$spaceId/list/$listId/task/$taskId'
      preLoaderRoute: typeof SpaceSpaceIdListListIdTaskTaskIdRouteImport
      parentRoute: typeof SpaceSpaceIdListListIdRoute
    }
    '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': {
      id: '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
      path: '/subtask/$subtaskId'
      fullPath: '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
      preLoaderRoute: typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRouteImport
      parentRoute: typeof SpaceSpaceIdListListIdTaskTaskIdRoute
    }
  }
}

interface FounderSettingsRouteChildren {
  FounderSettingsUsersIdRoute: typeof FounderSettingsUsersIdRoute
}

const FounderSettingsRouteChildren: FounderSettingsRouteChildren = {
  FounderSettingsUsersIdRoute: FounderSettingsUsersIdRoute,
}

const FounderSettingsRouteWithChildren = FounderSettingsRoute._addFileChildren(
  FounderSettingsRouteChildren,
)

interface FounderTeamRouteChildren {
  FounderTeamJobsJobIdRoute: typeof FounderTeamJobsJobIdRoute
}

const FounderTeamRouteChildren: FounderTeamRouteChildren = {
  FounderTeamJobsJobIdRoute: FounderTeamJobsJobIdRoute,
}

const FounderTeamRouteWithChildren = FounderTeamRoute._addFileChildren(
  FounderTeamRouteChildren,
)

interface FounderRouteChildren {
  FounderAiAgentsRoute: typeof FounderAiAgentsRoute
  FounderClientsRoute: typeof FounderClientsRoute
  FounderFinanceRoute: typeof FounderFinanceRoute
  FounderInitiativesRoute: typeof FounderInitiativesRoute
  FounderMarketIntelRoute: typeof FounderMarketIntelRoute
  FounderNetworkRoute: typeof FounderNetworkRoute
  FounderPipelineRoute: typeof FounderPipelineRoute
  FounderSettingsRoute: typeof FounderSettingsRouteWithChildren
  FounderTeamRoute: typeof FounderTeamRouteWithChildren
  FounderVenturesRoute: typeof FounderVenturesRoute
  FounderIndexRoute: typeof FounderIndexRoute
}

const FounderRouteChildren: FounderRouteChildren = {
  FounderAiAgentsRoute: FounderAiAgentsRoute,
  FounderClientsRoute: FounderClientsRoute,
  FounderFinanceRoute: FounderFinanceRoute,
  FounderInitiativesRoute: FounderInitiativesRoute,
  FounderMarketIntelRoute: FounderMarketIntelRoute,
  FounderNetworkRoute: FounderNetworkRoute,
  FounderPipelineRoute: FounderPipelineRoute,
  FounderSettingsRoute: FounderSettingsRouteWithChildren,
  FounderTeamRoute: FounderTeamRouteWithChildren,
  FounderVenturesRoute: FounderVenturesRoute,
  FounderIndexRoute: FounderIndexRoute,
}

const FounderRouteWithChildren =
  FounderRoute._addFileChildren(FounderRouteChildren)

interface SpaceSpaceIdListListIdTaskTaskIdRouteChildren {
  SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute: typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}

const SpaceSpaceIdListListIdTaskTaskIdRouteChildren: SpaceSpaceIdListListIdTaskTaskIdRouteChildren =
  {
    SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute:
      SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute,
  }

const SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren =
  SpaceSpaceIdListListIdTaskTaskIdRoute._addFileChildren(
    SpaceSpaceIdListListIdTaskTaskIdRouteChildren,
  )

interface SpaceSpaceIdListListIdRouteChildren {
  SpaceSpaceIdListListIdTaskTaskIdRoute: typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
}

const SpaceSpaceIdListListIdRouteChildren: SpaceSpaceIdListListIdRouteChildren =
  {
    SpaceSpaceIdListListIdTaskTaskIdRoute:
      SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren,
  }

const SpaceSpaceIdListListIdRouteWithChildren =
  SpaceSpaceIdListListIdRoute._addFileChildren(
    SpaceSpaceIdListListIdRouteChildren,
  )

interface SpaceSpaceIdRouteChildren {
  SpaceSpaceIdFolderFolderIdRoute: typeof SpaceSpaceIdFolderFolderIdRoute
  SpaceSpaceIdListListIdRoute: typeof SpaceSpaceIdListListIdRouteWithChildren
}

const SpaceSpaceIdRouteChildren: SpaceSpaceIdRouteChildren = {
  SpaceSpaceIdFolderFolderIdRoute: SpaceSpaceIdFolderFolderIdRoute,
  SpaceSpaceIdListListIdRoute: SpaceSpaceIdListListIdRouteWithChildren,
}

const SpaceSpaceIdRouteWithChildren = SpaceSpaceIdRoute._addFileChildren(
  SpaceSpaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRoute,
  FilesRoute: FilesRoute,
  FounderRoute: FounderRouteWithChildren,
  InboxRoute: InboxRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  PeopleIdRoute: PeopleIdRoute,
  PillarPillarIdRoute: PillarPillarIdRoute,
  SpaceSpaceIdRoute: SpaceSpaceIdRouteWithChildren,
  TeamCheckinsRoute: TeamCheckinsRoute,
  TeamHiringRoute: TeamHiringRoute,
  TeamWorkloadRoute: TeamWorkloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
