/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrgRouteImport } from './routes/org'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as OrgMembersRouteImport } from './routes/org.members'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRoute
  '/inbox': typeof InboxRoute
  '/org': typeof OrgRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/tasks': typeof TasksRoute
  '/org/members': typeof OrgMembersRoute
  '/org/': typeof OrgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/tasks': typeof TasksRoute
  '/org/members': typeof OrgMembersRoute
  '/org': typeof OrgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRoute
  '/inbox': typeof InboxRoute
  '/org': typeof OrgRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/tasks': typeof TasksRoute
  '/org/members': typeof OrgMembersRoute
  '/org/': typeof OrgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/org'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/org/members'
    | '/org/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/org/members'
    | '/org'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/org'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/org/members'
    | '/org/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FilesRoute: typeof FilesRoute
  FounderRoute: typeof FounderRoute
  InboxRoute: typeof InboxRoute
  OrgRoute: typeof OrgRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SpacesRoute: typeof SpacesRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/members': {
      id: '/org/members'
      path: '/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgMembersRoute: typeof OrgMembersRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgMembersRoute: OrgMembersRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FilesRoute: FilesRoute,
  FounderRoute: FounderRoute,
  InboxRoute: InboxRoute,
  OrgRoute: OrgRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SpacesRoute: SpacesRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
