/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrgRouteImport } from './routes/org'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as SpaceSpaceIdRouteImport } from './routes/space.$spaceId'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as OrgSubscriptionsRouteImport } from './routes/org.subscriptions'
import { Route as OrgSettingsRouteImport } from './routes/org.settings'
import { Route as OrgMembersRouteImport } from './routes/org.members'
import { Route as OrgFinancialRouteImport } from './routes/org.financial'
import { Route as SpaceSpaceIdListListIdRouteImport } from './routes/space.$spaceId.list.$listId'
import { Route as SpaceSpaceIdFolderFolderIdRouteImport } from './routes/space.$spaceId.folder.$folderId'
import { Route as SpaceSpaceIdListListIdTaskTaskIdRouteImport } from './routes/space.$spaceId.list.$listId.task.$taskId'
import { Route as SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRouteImport } from './routes/space.$spaceId.list.$listId.task.$taskId.subtask.$subtaskId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const SpaceSpaceIdRoute = SpaceSpaceIdRouteImport.update({
  id: '/space/$spaceId',
  path: '/space/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSubscriptionsRoute = OrgSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgRoute,
} as any)
const OrgFinancialRoute = OrgFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => OrgRoute,
} as any)
const SpaceSpaceIdListListIdRoute = SpaceSpaceIdListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => SpaceSpaceIdRoute,
} as any)
const SpaceSpaceIdFolderFolderIdRoute =
  SpaceSpaceIdFolderFolderIdRouteImport.update({
    id: '/folder/$folderId',
    path: '/folder/$folderId',
    getParentRoute: () => SpaceSpaceIdRoute,
  } as any)
const SpaceSpaceIdListListIdTaskTaskIdRoute =
  SpaceSpaceIdListListIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => SpaceSpaceIdListListIdRoute,
  } as any)
const SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute =
  SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRouteImport.update({
    id: '/subtask/$subtaskId',
    path: '/subtask/$subtaskId',
    getParentRoute: () => SpaceSpaceIdListListIdTaskTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRoute
  '/inbox': typeof InboxRoute
  '/org': typeof OrgRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/tasks': typeof TasksRoute
  '/org/financial': typeof OrgFinancialRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/subscriptions': typeof OrgSubscriptionsRoute
  '/people/$id': typeof PeopleIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/org/': typeof OrgIndexRoute
  '/space/$spaceId/folder/$folderId': typeof SpaceSpaceIdFolderFolderIdRoute
  '/space/$spaceId/list/$listId': typeof SpaceSpaceIdListListIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId': typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/tasks': typeof TasksRoute
  '/org/financial': typeof OrgFinancialRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/subscriptions': typeof OrgSubscriptionsRoute
  '/people/$id': typeof PeopleIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/org': typeof OrgIndexRoute
  '/space/$spaceId/folder/$folderId': typeof SpaceSpaceIdFolderFolderIdRoute
  '/space/$spaceId/list/$listId': typeof SpaceSpaceIdListListIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId': typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/files': typeof FilesRoute
  '/founder': typeof FounderRoute
  '/inbox': typeof InboxRoute
  '/org': typeof OrgRouteWithChildren
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/tasks': typeof TasksRoute
  '/org/financial': typeof OrgFinancialRoute
  '/org/members': typeof OrgMembersRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/subscriptions': typeof OrgSubscriptionsRoute
  '/people/$id': typeof PeopleIdRoute
  '/space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/org/': typeof OrgIndexRoute
  '/space/$spaceId/folder/$folderId': typeof SpaceSpaceIdFolderFolderIdRoute
  '/space/$spaceId/list/$listId': typeof SpaceSpaceIdListListIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId': typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
  '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/org'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/org/financial'
    | '/org/members'
    | '/org/settings'
    | '/org/subscriptions'
    | '/people/$id'
    | '/space/$spaceId'
    | '/org/'
    | '/space/$spaceId/folder/$folderId'
    | '/space/$spaceId/list/$listId'
    | '/space/$spaceId/list/$listId/task/$taskId'
    | '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/org/financial'
    | '/org/members'
    | '/org/settings'
    | '/org/subscriptions'
    | '/people/$id'
    | '/space/$spaceId'
    | '/org'
    | '/space/$spaceId/folder/$folderId'
    | '/space/$spaceId/list/$listId'
    | '/space/$spaceId/list/$listId/task/$taskId'
    | '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/files'
    | '/founder'
    | '/inbox'
    | '/org'
    | '/settings'
    | '/spaces'
    | '/tasks'
    | '/org/financial'
    | '/org/members'
    | '/org/settings'
    | '/org/subscriptions'
    | '/people/$id'
    | '/space/$spaceId'
    | '/org/'
    | '/space/$spaceId/folder/$folderId'
    | '/space/$spaceId/list/$listId'
    | '/space/$spaceId/list/$listId/task/$taskId'
    | '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FilesRoute: typeof FilesRoute
  FounderRoute: typeof FounderRoute
  InboxRoute: typeof InboxRoute
  OrgRoute: typeof OrgRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SpacesRoute: typeof SpacesRoute
  TasksRoute: typeof TasksRoute
  PeopleIdRoute: typeof PeopleIdRoute
  SpaceSpaceIdRoute: typeof SpaceSpaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/space/$spaceId': {
      id: '/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/space/$spaceId'
      preLoaderRoute: typeof SpaceSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/subscriptions': {
      id: '/org/subscriptions'
      path: '/subscriptions'
      fullPath: '/org/subscriptions'
      preLoaderRoute: typeof OrgSubscriptionsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/members': {
      id: '/org/members'
      path: '/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/financial': {
      id: '/org/financial'
      path: '/financial'
      fullPath: '/org/financial'
      preLoaderRoute: typeof OrgFinancialRouteImport
      parentRoute: typeof OrgRoute
    }
    '/space/$spaceId/list/$listId': {
      id: '/space/$spaceId/list/$listId'
      path: '/list/$listId'
      fullPath: '/space/$spaceId/list/$listId'
      preLoaderRoute: typeof SpaceSpaceIdListListIdRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/space/$spaceId/folder/$folderId': {
      id: '/space/$spaceId/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/space/$spaceId/folder/$folderId'
      preLoaderRoute: typeof SpaceSpaceIdFolderFolderIdRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/space/$spaceId/list/$listId/task/$taskId': {
      id: '/space/$spaceId/list/$listId/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/space/$spaceId/list/$listId/task/$taskId'
      preLoaderRoute: typeof SpaceSpaceIdListListIdTaskTaskIdRouteImport
      parentRoute: typeof SpaceSpaceIdListListIdRoute
    }
    '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId': {
      id: '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
      path: '/subtask/$subtaskId'
      fullPath: '/space/$spaceId/list/$listId/task/$taskId/subtask/$subtaskId'
      preLoaderRoute: typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRouteImport
      parentRoute: typeof SpaceSpaceIdListListIdTaskTaskIdRoute
    }
  }
}

interface OrgRouteChildren {
  OrgFinancialRoute: typeof OrgFinancialRoute
  OrgMembersRoute: typeof OrgMembersRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  OrgSubscriptionsRoute: typeof OrgSubscriptionsRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgFinancialRoute: OrgFinancialRoute,
  OrgMembersRoute: OrgMembersRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  OrgSubscriptionsRoute: OrgSubscriptionsRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

interface SpaceSpaceIdListListIdTaskTaskIdRouteChildren {
  SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute: typeof SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute
}

const SpaceSpaceIdListListIdTaskTaskIdRouteChildren: SpaceSpaceIdListListIdTaskTaskIdRouteChildren =
  {
    SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute:
      SpaceSpaceIdListListIdTaskTaskIdSubtaskSubtaskIdRoute,
  }

const SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren =
  SpaceSpaceIdListListIdTaskTaskIdRoute._addFileChildren(
    SpaceSpaceIdListListIdTaskTaskIdRouteChildren,
  )

interface SpaceSpaceIdListListIdRouteChildren {
  SpaceSpaceIdListListIdTaskTaskIdRoute: typeof SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren
}

const SpaceSpaceIdListListIdRouteChildren: SpaceSpaceIdListListIdRouteChildren =
  {
    SpaceSpaceIdListListIdTaskTaskIdRoute:
      SpaceSpaceIdListListIdTaskTaskIdRouteWithChildren,
  }

const SpaceSpaceIdListListIdRouteWithChildren =
  SpaceSpaceIdListListIdRoute._addFileChildren(
    SpaceSpaceIdListListIdRouteChildren,
  )

interface SpaceSpaceIdRouteChildren {
  SpaceSpaceIdFolderFolderIdRoute: typeof SpaceSpaceIdFolderFolderIdRoute
  SpaceSpaceIdListListIdRoute: typeof SpaceSpaceIdListListIdRouteWithChildren
}

const SpaceSpaceIdRouteChildren: SpaceSpaceIdRouteChildren = {
  SpaceSpaceIdFolderFolderIdRoute: SpaceSpaceIdFolderFolderIdRoute,
  SpaceSpaceIdListListIdRoute: SpaceSpaceIdListListIdRouteWithChildren,
}

const SpaceSpaceIdRouteWithChildren = SpaceSpaceIdRoute._addFileChildren(
  SpaceSpaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FilesRoute: FilesRoute,
  FounderRoute: FounderRoute,
  InboxRoute: InboxRoute,
  OrgRoute: OrgRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SpacesRoute: SpacesRoute,
  TasksRoute: TasksRoute,
  PeopleIdRoute: PeopleIdRoute,
  SpaceSpaceIdRoute: SpaceSpaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
